query hello {
  Hello
}

mutation add($x: Int!, $y: Int!) {
  add(x: $x, y: $y)
}

mutation multiply($x: Int!, $y: Int!) {
  add(x: $x, y: $y)
}

query dogs {
  dogs {
    name
    coat
    owner {
      firstname
      lastname
    }
  }
}

mutation createNotification($message: String!) {
  createNotification(message: $message)
}

subscription newNotification {
  newNotification
}
